# Generated by Django 4.2 on 2023-05-02 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_filter_history_page_video_text_team_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='teams',
        ),
        migrations.AddField(
            model_name='team',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
