# Generated by Django 4.2 on 2023-05-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_team_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_members',
        ),
        migrations.AddField(
            model_name='customuser',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, to='core.team'),
        ),
    ]
