# Generated by Django 4.2 on 2023-05-02 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_comment_id_alter_customuser_teams_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='author',
        ),
    ]
