# Generated by Django 4.2 on 2023-05-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_team_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='teams',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, to='core.team'),
        ),
    ]
