# Generated by Django 4.2 on 2024-01-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_collaborators_customer_folder_price_pricerelation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='workspaces/%Y/%m/%d/'),
        ),
    ]
